// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skrshop/internal/data/ent/authmsmenu"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthMsMenuCreate is the builder for creating a AuthMsMenu entity.
type AuthMsMenuCreate struct {
	config
	mutation *AuthMsMenuMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (ammc *AuthMsMenuCreate) SetStatus(i int8) *AuthMsMenuCreate {
	ammc.mutation.SetStatus(i)
	return ammc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ammc *AuthMsMenuCreate) SetNillableStatus(i *int8) *AuthMsMenuCreate {
	if i != nil {
		ammc.SetStatus(*i)
	}
	return ammc
}

// SetCreateAt sets the "create_at" field.
func (ammc *AuthMsMenuCreate) SetCreateAt(t time.Time) *AuthMsMenuCreate {
	ammc.mutation.SetCreateAt(t)
	return ammc
}

// SetUpdateAt sets the "update_at" field.
func (ammc *AuthMsMenuCreate) SetUpdateAt(t time.Time) *AuthMsMenuCreate {
	ammc.mutation.SetUpdateAt(t)
	return ammc
}

// Mutation returns the AuthMsMenuMutation object of the builder.
func (ammc *AuthMsMenuCreate) Mutation() *AuthMsMenuMutation {
	return ammc.mutation
}

// Save creates the AuthMsMenu in the database.
func (ammc *AuthMsMenuCreate) Save(ctx context.Context) (*AuthMsMenu, error) {
	var (
		err  error
		node *AuthMsMenu
	)
	ammc.defaults()
	if len(ammc.hooks) == 0 {
		if err = ammc.check(); err != nil {
			return nil, err
		}
		node, err = ammc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthMsMenuMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ammc.check(); err != nil {
				return nil, err
			}
			ammc.mutation = mutation
			node, err = ammc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ammc.hooks) - 1; i >= 0; i-- {
			mut = ammc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ammc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ammc *AuthMsMenuCreate) SaveX(ctx context.Context) *AuthMsMenu {
	v, err := ammc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (ammc *AuthMsMenuCreate) defaults() {
	if _, ok := ammc.mutation.Status(); !ok {
		v := authmsmenu.DefaultStatus
		ammc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ammc *AuthMsMenuCreate) check() error {
	if _, ok := ammc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if _, ok := ammc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	if _, ok := ammc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New("ent: missing required field \"update_at\"")}
	}
	return nil
}

func (ammc *AuthMsMenuCreate) sqlSave(ctx context.Context) (*AuthMsMenu, error) {
	_node, _spec := ammc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ammc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ammc *AuthMsMenuCreate) createSpec() (*AuthMsMenu, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthMsMenu{config: ammc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: authmsmenu.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authmsmenu.FieldID,
			},
		}
	)
	if value, ok := ammc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: authmsmenu.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := ammc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: authmsmenu.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := ammc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: authmsmenu.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	return _node, _spec
}

// AuthMsMenuCreateBulk is the builder for creating many AuthMsMenu entities in bulk.
type AuthMsMenuCreateBulk struct {
	config
	builders []*AuthMsMenuCreate
}

// Save creates the AuthMsMenu entities in the database.
func (ammcb *AuthMsMenuCreateBulk) Save(ctx context.Context) ([]*AuthMsMenu, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ammcb.builders))
	nodes := make([]*AuthMsMenu, len(ammcb.builders))
	mutators := make([]Mutator, len(ammcb.builders))
	for i := range ammcb.builders {
		func(i int, root context.Context) {
			builder := ammcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthMsMenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ammcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ammcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ammcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ammcb *AuthMsMenuCreateBulk) SaveX(ctx context.Context) []*AuthMsMenu {
	v, err := ammcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
