// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"skrshop/internal/data/ent/authmsmenu"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// AuthMsMenu is the model entity for the AuthMsMenu schema.
type AuthMsMenu struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 状态 1:enable, 0:disable, -1:deleted
	Status int8 `json:"status,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 更新时间
	UpdateAt time.Time `json:"update_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthMsMenu) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case authmsmenu.FieldID, authmsmenu.FieldStatus:
			values[i] = &sql.NullInt64{}
		case authmsmenu.FieldCreateAt, authmsmenu.FieldUpdateAt:
			values[i] = &sql.NullTime{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type AuthMsMenu", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthMsMenu fields.
func (amm *AuthMsMenu) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authmsmenu.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			amm.ID = int(value.Int64)
		case authmsmenu.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				amm.Status = int8(value.Int64)
			}
		case authmsmenu.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				amm.CreateAt = value.Time
			}
		case authmsmenu.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				amm.UpdateAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this AuthMsMenu.
// Note that you need to call AuthMsMenu.Unwrap() before calling this method if this AuthMsMenu
// was returned from a transaction, and the transaction was committed or rolled back.
func (amm *AuthMsMenu) Update() *AuthMsMenuUpdateOne {
	return (&AuthMsMenuClient{config: amm.config}).UpdateOne(amm)
}

// Unwrap unwraps the AuthMsMenu entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (amm *AuthMsMenu) Unwrap() *AuthMsMenu {
	tx, ok := amm.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthMsMenu is not a transactional entity")
	}
	amm.config.driver = tx.drv
	return amm
}

// String implements the fmt.Stringer.
func (amm *AuthMsMenu) String() string {
	var builder strings.Builder
	builder.WriteString("AuthMsMenu(")
	builder.WriteString(fmt.Sprintf("id=%v", amm.ID))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", amm.Status))
	builder.WriteString(", create_at=")
	builder.WriteString(amm.CreateAt.Format(time.ANSIC))
	builder.WriteString(", update_at=")
	builder.WriteString(amm.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuthMsMenus is a parsable slice of AuthMsMenu.
type AuthMsMenus []*AuthMsMenu

func (amm AuthMsMenus) config(cfg config) {
	for _i := range amm {
		amm[_i].config = cfg
	}
}
