// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skrshop/internal/data/ent/authitem"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthItemCreate is the builder for creating a AuthItem entity.
type AuthItemCreate struct {
	config
	mutation *AuthItemMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (aic *AuthItemCreate) SetStatus(i int8) *AuthItemCreate {
	aic.mutation.SetStatus(i)
	return aic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aic *AuthItemCreate) SetNillableStatus(i *int8) *AuthItemCreate {
	if i != nil {
		aic.SetStatus(*i)
	}
	return aic
}

// SetCreateAt sets the "create_at" field.
func (aic *AuthItemCreate) SetCreateAt(t time.Time) *AuthItemCreate {
	aic.mutation.SetCreateAt(t)
	return aic
}

// SetUpdateAt sets the "update_at" field.
func (aic *AuthItemCreate) SetUpdateAt(t time.Time) *AuthItemCreate {
	aic.mutation.SetUpdateAt(t)
	return aic
}

// Mutation returns the AuthItemMutation object of the builder.
func (aic *AuthItemCreate) Mutation() *AuthItemMutation {
	return aic.mutation
}

// Save creates the AuthItem in the database.
func (aic *AuthItemCreate) Save(ctx context.Context) (*AuthItem, error) {
	var (
		err  error
		node *AuthItem
	)
	aic.defaults()
	if len(aic.hooks) == 0 {
		if err = aic.check(); err != nil {
			return nil, err
		}
		node, err = aic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aic.check(); err != nil {
				return nil, err
			}
			aic.mutation = mutation
			node, err = aic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aic.hooks) - 1; i >= 0; i-- {
			mut = aic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aic *AuthItemCreate) SaveX(ctx context.Context) *AuthItem {
	v, err := aic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (aic *AuthItemCreate) defaults() {
	if _, ok := aic.mutation.Status(); !ok {
		v := authitem.DefaultStatus
		aic.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aic *AuthItemCreate) check() error {
	if _, ok := aic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if _, ok := aic.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	if _, ok := aic.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New("ent: missing required field \"update_at\"")}
	}
	return nil
}

func (aic *AuthItemCreate) sqlSave(ctx context.Context) (*AuthItem, error) {
	_node, _spec := aic.createSpec()
	if err := sqlgraph.CreateNode(ctx, aic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aic *AuthItemCreate) createSpec() (*AuthItem, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthItem{config: aic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: authitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authitem.FieldID,
			},
		}
	)
	if value, ok := aic.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: authitem.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := aic.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: authitem.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := aic.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: authitem.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	return _node, _spec
}

// AuthItemCreateBulk is the builder for creating many AuthItem entities in bulk.
type AuthItemCreateBulk struct {
	config
	builders []*AuthItemCreate
}

// Save creates the AuthItem entities in the database.
func (aicb *AuthItemCreateBulk) Save(ctx context.Context) ([]*AuthItem, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aicb.builders))
	nodes := make([]*AuthItem, len(aicb.builders))
	mutators := make([]Mutator, len(aicb.builders))
	for i := range aicb.builders {
		func(i int, root context.Context) {
			builder := aicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aicb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aicb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aicb *AuthItemCreateBulk) SaveX(ctx context.Context) []*AuthItem {
	v, err := aicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
