// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productattrvalue"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttrValueQuery is the builder for querying ProductAttrValue entities.
type ProductAttrValueQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProductAttrValue
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductAttrValueQuery builder.
func (pavq *ProductAttrValueQuery) Where(ps ...predicate.ProductAttrValue) *ProductAttrValueQuery {
	pavq.predicates = append(pavq.predicates, ps...)
	return pavq
}

// Limit adds a limit step to the query.
func (pavq *ProductAttrValueQuery) Limit(limit int) *ProductAttrValueQuery {
	pavq.limit = &limit
	return pavq
}

// Offset adds an offset step to the query.
func (pavq *ProductAttrValueQuery) Offset(offset int) *ProductAttrValueQuery {
	pavq.offset = &offset
	return pavq
}

// Order adds an order step to the query.
func (pavq *ProductAttrValueQuery) Order(o ...OrderFunc) *ProductAttrValueQuery {
	pavq.order = append(pavq.order, o...)
	return pavq
}

// First returns the first ProductAttrValue entity from the query.
// Returns a *NotFoundError when no ProductAttrValue was found.
func (pavq *ProductAttrValueQuery) First(ctx context.Context) (*ProductAttrValue, error) {
	nodes, err := pavq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productattrvalue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) FirstX(ctx context.Context) *ProductAttrValue {
	node, err := pavq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductAttrValue ID from the query.
// Returns a *NotFoundError when no ProductAttrValue ID was found.
func (pavq *ProductAttrValueQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pavq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productattrvalue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) FirstIDX(ctx context.Context) int {
	id, err := pavq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductAttrValue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ProductAttrValue entity is not found.
// Returns a *NotFoundError when no ProductAttrValue entities are found.
func (pavq *ProductAttrValueQuery) Only(ctx context.Context) (*ProductAttrValue, error) {
	nodes, err := pavq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productattrvalue.Label}
	default:
		return nil, &NotSingularError{productattrvalue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) OnlyX(ctx context.Context) *ProductAttrValue {
	node, err := pavq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductAttrValue ID in the query.
// Returns a *NotSingularError when exactly one ProductAttrValue ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pavq *ProductAttrValueQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pavq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = &NotSingularError{productattrvalue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) OnlyIDX(ctx context.Context) int {
	id, err := pavq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductAttrValues.
func (pavq *ProductAttrValueQuery) All(ctx context.Context) ([]*ProductAttrValue, error) {
	if err := pavq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pavq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) AllX(ctx context.Context) []*ProductAttrValue {
	nodes, err := pavq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductAttrValue IDs.
func (pavq *ProductAttrValueQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pavq.Select(productattrvalue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) IDsX(ctx context.Context) []int {
	ids, err := pavq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pavq *ProductAttrValueQuery) Count(ctx context.Context) (int, error) {
	if err := pavq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pavq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) CountX(ctx context.Context) int {
	count, err := pavq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pavq *ProductAttrValueQuery) Exist(ctx context.Context) (bool, error) {
	if err := pavq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pavq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pavq *ProductAttrValueQuery) ExistX(ctx context.Context) bool {
	exist, err := pavq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductAttrValueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pavq *ProductAttrValueQuery) Clone() *ProductAttrValueQuery {
	if pavq == nil {
		return nil
	}
	return &ProductAttrValueQuery{
		config:     pavq.config,
		limit:      pavq.limit,
		offset:     pavq.offset,
		order:      append([]OrderFunc{}, pavq.order...),
		predicates: append([]predicate.ProductAttrValue{}, pavq.predicates...),
		// clone intermediate query.
		sql:  pavq.sql.Clone(),
		path: pavq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status int8 `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductAttrValue.Query().
//		GroupBy(productattrvalue.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pavq *ProductAttrValueQuery) GroupBy(field string, fields ...string) *ProductAttrValueGroupBy {
	group := &ProductAttrValueGroupBy{config: pavq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pavq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pavq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status int8 `json:"status,omitempty"`
//	}
//
//	client.ProductAttrValue.Query().
//		Select(productattrvalue.FieldStatus).
//		Scan(ctx, &v)
//
func (pavq *ProductAttrValueQuery) Select(field string, fields ...string) *ProductAttrValueSelect {
	pavq.fields = append([]string{field}, fields...)
	return &ProductAttrValueSelect{ProductAttrValueQuery: pavq}
}

func (pavq *ProductAttrValueQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pavq.fields {
		if !productattrvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pavq.path != nil {
		prev, err := pavq.path(ctx)
		if err != nil {
			return err
		}
		pavq.sql = prev
	}
	return nil
}

func (pavq *ProductAttrValueQuery) sqlAll(ctx context.Context) ([]*ProductAttrValue, error) {
	var (
		nodes = []*ProductAttrValue{}
		_spec = pavq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProductAttrValue{config: pavq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pavq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pavq *ProductAttrValueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pavq.querySpec()
	return sqlgraph.CountNodes(ctx, pavq.driver, _spec)
}

func (pavq *ProductAttrValueQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pavq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (pavq *ProductAttrValueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productattrvalue.Table,
			Columns: productattrvalue.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattrvalue.FieldID,
			},
		},
		From:   pavq.sql,
		Unique: true,
	}
	if fields := pavq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productattrvalue.FieldID)
		for i := range fields {
			if fields[i] != productattrvalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pavq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pavq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pavq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pavq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, productattrvalue.ValidColumn)
			}
		}
	}
	return _spec
}

func (pavq *ProductAttrValueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pavq.driver.Dialect())
	t1 := builder.Table(productattrvalue.Table)
	selector := builder.Select(t1.Columns(productattrvalue.Columns...)...).From(t1)
	if pavq.sql != nil {
		selector = pavq.sql
		selector.Select(selector.Columns(productattrvalue.Columns...)...)
	}
	for _, p := range pavq.predicates {
		p(selector)
	}
	for _, p := range pavq.order {
		p(selector, productattrvalue.ValidColumn)
	}
	if offset := pavq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pavq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductAttrValueGroupBy is the group-by builder for ProductAttrValue entities.
type ProductAttrValueGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pavgb *ProductAttrValueGroupBy) Aggregate(fns ...AggregateFunc) *ProductAttrValueGroupBy {
	pavgb.fns = append(pavgb.fns, fns...)
	return pavgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pavgb *ProductAttrValueGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pavgb.path(ctx)
	if err != nil {
		return err
	}
	pavgb.sql = query
	return pavgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pavgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pavgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pavgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) StringsX(ctx context.Context) []string {
	v, err := pavgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pavgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) StringX(ctx context.Context) string {
	v, err := pavgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pavgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pavgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) IntsX(ctx context.Context) []int {
	v, err := pavgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pavgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) IntX(ctx context.Context) int {
	v, err := pavgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pavgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pavgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pavgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pavgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pavgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pavgb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pavgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pavgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pavgb *ProductAttrValueGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pavgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pavgb *ProductAttrValueGroupBy) BoolX(ctx context.Context) bool {
	v, err := pavgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pavgb *ProductAttrValueGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pavgb.fields {
		if !productattrvalue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pavgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pavgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pavgb *ProductAttrValueGroupBy) sqlQuery() *sql.Selector {
	selector := pavgb.sql
	columns := make([]string, 0, len(pavgb.fields)+len(pavgb.fns))
	columns = append(columns, pavgb.fields...)
	for _, fn := range pavgb.fns {
		columns = append(columns, fn(selector, productattrvalue.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(pavgb.fields...)
}

// ProductAttrValueSelect is the builder for selecting fields of ProductAttrValue entities.
type ProductAttrValueSelect struct {
	*ProductAttrValueQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pavs *ProductAttrValueSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pavs.prepareQuery(ctx); err != nil {
		return err
	}
	pavs.sql = pavs.ProductAttrValueQuery.sqlQuery(ctx)
	return pavs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pavs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pavs.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pavs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) StringsX(ctx context.Context) []string {
	v, err := pavs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pavs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) StringX(ctx context.Context) string {
	v, err := pavs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pavs.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pavs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) IntsX(ctx context.Context) []int {
	v, err := pavs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pavs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) IntX(ctx context.Context) int {
	v, err := pavs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pavs.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pavs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pavs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pavs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) Float64X(ctx context.Context) float64 {
	v, err := pavs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pavs.fields) > 1 {
		return nil, errors.New("ent: ProductAttrValueSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pavs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) BoolsX(ctx context.Context) []bool {
	v, err := pavs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pavs *ProductAttrValueSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pavs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattrvalue.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrValueSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pavs *ProductAttrValueSelect) BoolX(ctx context.Context) bool {
	v, err := pavs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pavs *ProductAttrValueSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pavs.sqlQuery().Query()
	if err := pavs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pavs *ProductAttrValueSelect) sqlQuery() sql.Querier {
	selector := pavs.sql
	selector.Select(selector.Columns(pavs.fields...)...)
	return selector
}
