// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productattr"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttrQuery is the builder for querying ProductAttr entities.
type ProductAttrQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProductAttr
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductAttrQuery builder.
func (paq *ProductAttrQuery) Where(ps ...predicate.ProductAttr) *ProductAttrQuery {
	paq.predicates = append(paq.predicates, ps...)
	return paq
}

// Limit adds a limit step to the query.
func (paq *ProductAttrQuery) Limit(limit int) *ProductAttrQuery {
	paq.limit = &limit
	return paq
}

// Offset adds an offset step to the query.
func (paq *ProductAttrQuery) Offset(offset int) *ProductAttrQuery {
	paq.offset = &offset
	return paq
}

// Order adds an order step to the query.
func (paq *ProductAttrQuery) Order(o ...OrderFunc) *ProductAttrQuery {
	paq.order = append(paq.order, o...)
	return paq
}

// First returns the first ProductAttr entity from the query.
// Returns a *NotFoundError when no ProductAttr was found.
func (paq *ProductAttrQuery) First(ctx context.Context) (*ProductAttr, error) {
	nodes, err := paq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productattr.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (paq *ProductAttrQuery) FirstX(ctx context.Context) *ProductAttr {
	node, err := paq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductAttr ID from the query.
// Returns a *NotFoundError when no ProductAttr ID was found.
func (paq *ProductAttrQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = paq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productattr.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (paq *ProductAttrQuery) FirstIDX(ctx context.Context) int {
	id, err := paq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductAttr entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ProductAttr entity is not found.
// Returns a *NotFoundError when no ProductAttr entities are found.
func (paq *ProductAttrQuery) Only(ctx context.Context) (*ProductAttr, error) {
	nodes, err := paq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productattr.Label}
	default:
		return nil, &NotSingularError{productattr.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (paq *ProductAttrQuery) OnlyX(ctx context.Context) *ProductAttr {
	node, err := paq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductAttr ID in the query.
// Returns a *NotSingularError when exactly one ProductAttr ID is not found.
// Returns a *NotFoundError when no entities are found.
func (paq *ProductAttrQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = paq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = &NotSingularError{productattr.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (paq *ProductAttrQuery) OnlyIDX(ctx context.Context) int {
	id, err := paq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductAttrs.
func (paq *ProductAttrQuery) All(ctx context.Context) ([]*ProductAttr, error) {
	if err := paq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return paq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (paq *ProductAttrQuery) AllX(ctx context.Context) []*ProductAttr {
	nodes, err := paq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductAttr IDs.
func (paq *ProductAttrQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := paq.Select(productattr.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (paq *ProductAttrQuery) IDsX(ctx context.Context) []int {
	ids, err := paq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (paq *ProductAttrQuery) Count(ctx context.Context) (int, error) {
	if err := paq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return paq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (paq *ProductAttrQuery) CountX(ctx context.Context) int {
	count, err := paq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (paq *ProductAttrQuery) Exist(ctx context.Context) (bool, error) {
	if err := paq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return paq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (paq *ProductAttrQuery) ExistX(ctx context.Context) bool {
	exist, err := paq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductAttrQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (paq *ProductAttrQuery) Clone() *ProductAttrQuery {
	if paq == nil {
		return nil
	}
	return &ProductAttrQuery{
		config:     paq.config,
		limit:      paq.limit,
		offset:     paq.offset,
		order:      append([]OrderFunc{}, paq.order...),
		predicates: append([]predicate.ProductAttr{}, paq.predicates...),
		// clone intermediate query.
		sql:  paq.sql.Clone(),
		path: paq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status int8 `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductAttr.Query().
//		GroupBy(productattr.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (paq *ProductAttrQuery) GroupBy(field string, fields ...string) *ProductAttrGroupBy {
	group := &ProductAttrGroupBy{config: paq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := paq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return paq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status int8 `json:"status,omitempty"`
//	}
//
//	client.ProductAttr.Query().
//		Select(productattr.FieldStatus).
//		Scan(ctx, &v)
//
func (paq *ProductAttrQuery) Select(field string, fields ...string) *ProductAttrSelect {
	paq.fields = append([]string{field}, fields...)
	return &ProductAttrSelect{ProductAttrQuery: paq}
}

func (paq *ProductAttrQuery) prepareQuery(ctx context.Context) error {
	for _, f := range paq.fields {
		if !productattr.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if paq.path != nil {
		prev, err := paq.path(ctx)
		if err != nil {
			return err
		}
		paq.sql = prev
	}
	return nil
}

func (paq *ProductAttrQuery) sqlAll(ctx context.Context) ([]*ProductAttr, error) {
	var (
		nodes = []*ProductAttr{}
		_spec = paq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProductAttr{config: paq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, paq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (paq *ProductAttrQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := paq.querySpec()
	return sqlgraph.CountNodes(ctx, paq.driver, _spec)
}

func (paq *ProductAttrQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := paq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (paq *ProductAttrQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productattr.Table,
			Columns: productattr.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattr.FieldID,
			},
		},
		From:   paq.sql,
		Unique: true,
	}
	if fields := paq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productattr.FieldID)
		for i := range fields {
			if fields[i] != productattr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := paq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := paq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := paq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := paq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, productattr.ValidColumn)
			}
		}
	}
	return _spec
}

func (paq *ProductAttrQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(paq.driver.Dialect())
	t1 := builder.Table(productattr.Table)
	selector := builder.Select(t1.Columns(productattr.Columns...)...).From(t1)
	if paq.sql != nil {
		selector = paq.sql
		selector.Select(selector.Columns(productattr.Columns...)...)
	}
	for _, p := range paq.predicates {
		p(selector)
	}
	for _, p := range paq.order {
		p(selector, productattr.ValidColumn)
	}
	if offset := paq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := paq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductAttrGroupBy is the group-by builder for ProductAttr entities.
type ProductAttrGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pagb *ProductAttrGroupBy) Aggregate(fns ...AggregateFunc) *ProductAttrGroupBy {
	pagb.fns = append(pagb.fns, fns...)
	return pagb
}

// Scan applies the group-by query and scans the result into the given value.
func (pagb *ProductAttrGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pagb.path(ctx)
	if err != nil {
		return err
	}
	pagb.sql = query
	return pagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pagb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) StringsX(ctx context.Context) []string {
	v, err := pagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) StringX(ctx context.Context) string {
	v, err := pagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pagb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) IntsX(ctx context.Context) []int {
	v, err := pagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) IntX(ctx context.Context) int {
	v, err := pagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pagb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pagb.fields) > 1 {
		return nil, errors.New("ent: ProductAttrGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pagb *ProductAttrGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pagb *ProductAttrGroupBy) BoolX(ctx context.Context) bool {
	v, err := pagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pagb *ProductAttrGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pagb.fields {
		if !productattr.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pagb *ProductAttrGroupBy) sqlQuery() *sql.Selector {
	selector := pagb.sql
	columns := make([]string, 0, len(pagb.fields)+len(pagb.fns))
	columns = append(columns, pagb.fields...)
	for _, fn := range pagb.fns {
		columns = append(columns, fn(selector, productattr.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(pagb.fields...)
}

// ProductAttrSelect is the builder for selecting fields of ProductAttr entities.
type ProductAttrSelect struct {
	*ProductAttrQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pas *ProductAttrSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pas.prepareQuery(ctx); err != nil {
		return err
	}
	pas.sql = pas.ProductAttrQuery.sqlQuery(ctx)
	return pas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pas *ProductAttrSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pas.fields) > 1 {
		return nil, errors.New("ent: ProductAttrSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pas *ProductAttrSelect) StringsX(ctx context.Context) []string {
	v, err := pas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pas *ProductAttrSelect) StringX(ctx context.Context) string {
	v, err := pas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pas.fields) > 1 {
		return nil, errors.New("ent: ProductAttrSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pas *ProductAttrSelect) IntsX(ctx context.Context) []int {
	v, err := pas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pas *ProductAttrSelect) IntX(ctx context.Context) int {
	v, err := pas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pas.fields) > 1 {
		return nil, errors.New("ent: ProductAttrSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pas *ProductAttrSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pas *ProductAttrSelect) Float64X(ctx context.Context) float64 {
	v, err := pas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pas.fields) > 1 {
		return nil, errors.New("ent: ProductAttrSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pas *ProductAttrSelect) BoolsX(ctx context.Context) []bool {
	v, err := pas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pas *ProductAttrSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productattr.Label}
	default:
		err = fmt.Errorf("ent: ProductAttrSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pas *ProductAttrSelect) BoolX(ctx context.Context) bool {
	v, err := pas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pas *ProductAttrSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pas.sqlQuery().Query()
	if err := pas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pas *ProductAttrSelect) sqlQuery() sql.Querier {
	selector := pas.sql
	selector.Select(selector.Columns(pas.fields...)...)
	return selector
}
