// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productspuskuattrmap"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductSpuSkuAttrMapQuery is the builder for querying ProductSpuSkuAttrMap entities.
type ProductSpuSkuAttrMapQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.ProductSpuSkuAttrMap
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductSpuSkuAttrMapQuery builder.
func (pssamq *ProductSpuSkuAttrMapQuery) Where(ps ...predicate.ProductSpuSkuAttrMap) *ProductSpuSkuAttrMapQuery {
	pssamq.predicates = append(pssamq.predicates, ps...)
	return pssamq
}

// Limit adds a limit step to the query.
func (pssamq *ProductSpuSkuAttrMapQuery) Limit(limit int) *ProductSpuSkuAttrMapQuery {
	pssamq.limit = &limit
	return pssamq
}

// Offset adds an offset step to the query.
func (pssamq *ProductSpuSkuAttrMapQuery) Offset(offset int) *ProductSpuSkuAttrMapQuery {
	pssamq.offset = &offset
	return pssamq
}

// Order adds an order step to the query.
func (pssamq *ProductSpuSkuAttrMapQuery) Order(o ...OrderFunc) *ProductSpuSkuAttrMapQuery {
	pssamq.order = append(pssamq.order, o...)
	return pssamq
}

// First returns the first ProductSpuSkuAttrMap entity from the query.
// Returns a *NotFoundError when no ProductSpuSkuAttrMap was found.
func (pssamq *ProductSpuSkuAttrMapQuery) First(ctx context.Context) (*ProductSpuSkuAttrMap, error) {
	nodes, err := pssamq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productspuskuattrmap.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) FirstX(ctx context.Context) *ProductSpuSkuAttrMap {
	node, err := pssamq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductSpuSkuAttrMap ID from the query.
// Returns a *NotFoundError when no ProductSpuSkuAttrMap ID was found.
func (pssamq *ProductSpuSkuAttrMapQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pssamq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productspuskuattrmap.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) FirstIDX(ctx context.Context) int {
	id, err := pssamq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductSpuSkuAttrMap entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ProductSpuSkuAttrMap entity is not found.
// Returns a *NotFoundError when no ProductSpuSkuAttrMap entities are found.
func (pssamq *ProductSpuSkuAttrMapQuery) Only(ctx context.Context) (*ProductSpuSkuAttrMap, error) {
	nodes, err := pssamq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productspuskuattrmap.Label}
	default:
		return nil, &NotSingularError{productspuskuattrmap.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) OnlyX(ctx context.Context) *ProductSpuSkuAttrMap {
	node, err := pssamq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductSpuSkuAttrMap ID in the query.
// Returns a *NotSingularError when exactly one ProductSpuSkuAttrMap ID is not found.
// Returns a *NotFoundError when no entities are found.
func (pssamq *ProductSpuSkuAttrMapQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pssamq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = &NotSingularError{productspuskuattrmap.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) OnlyIDX(ctx context.Context) int {
	id, err := pssamq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductSpuSkuAttrMaps.
func (pssamq *ProductSpuSkuAttrMapQuery) All(ctx context.Context) ([]*ProductSpuSkuAttrMap, error) {
	if err := pssamq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pssamq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) AllX(ctx context.Context) []*ProductSpuSkuAttrMap {
	nodes, err := pssamq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductSpuSkuAttrMap IDs.
func (pssamq *ProductSpuSkuAttrMapQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pssamq.Select(productspuskuattrmap.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) IDsX(ctx context.Context) []int {
	ids, err := pssamq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pssamq *ProductSpuSkuAttrMapQuery) Count(ctx context.Context) (int, error) {
	if err := pssamq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pssamq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) CountX(ctx context.Context) int {
	count, err := pssamq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pssamq *ProductSpuSkuAttrMapQuery) Exist(ctx context.Context) (bool, error) {
	if err := pssamq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pssamq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pssamq *ProductSpuSkuAttrMapQuery) ExistX(ctx context.Context) bool {
	exist, err := pssamq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductSpuSkuAttrMapQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pssamq *ProductSpuSkuAttrMapQuery) Clone() *ProductSpuSkuAttrMapQuery {
	if pssamq == nil {
		return nil
	}
	return &ProductSpuSkuAttrMapQuery{
		config:     pssamq.config,
		limit:      pssamq.limit,
		offset:     pssamq.offset,
		order:      append([]OrderFunc{}, pssamq.order...),
		predicates: append([]predicate.ProductSpuSkuAttrMap{}, pssamq.predicates...),
		// clone intermediate query.
		sql:  pssamq.sql.Clone(),
		path: pssamq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateAt time.Time `json:"create_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductSpuSkuAttrMap.Query().
//		GroupBy(productspuskuattrmap.FieldCreateAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pssamq *ProductSpuSkuAttrMapQuery) GroupBy(field string, fields ...string) *ProductSpuSkuAttrMapGroupBy {
	group := &ProductSpuSkuAttrMapGroupBy{config: pssamq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pssamq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pssamq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateAt time.Time `json:"create_at,omitempty"`
//	}
//
//	client.ProductSpuSkuAttrMap.Query().
//		Select(productspuskuattrmap.FieldCreateAt).
//		Scan(ctx, &v)
//
func (pssamq *ProductSpuSkuAttrMapQuery) Select(field string, fields ...string) *ProductSpuSkuAttrMapSelect {
	pssamq.fields = append([]string{field}, fields...)
	return &ProductSpuSkuAttrMapSelect{ProductSpuSkuAttrMapQuery: pssamq}
}

func (pssamq *ProductSpuSkuAttrMapQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pssamq.fields {
		if !productspuskuattrmap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pssamq.path != nil {
		prev, err := pssamq.path(ctx)
		if err != nil {
			return err
		}
		pssamq.sql = prev
	}
	return nil
}

func (pssamq *ProductSpuSkuAttrMapQuery) sqlAll(ctx context.Context) ([]*ProductSpuSkuAttrMap, error) {
	var (
		nodes = []*ProductSpuSkuAttrMap{}
		_spec = pssamq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ProductSpuSkuAttrMap{config: pssamq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pssamq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pssamq *ProductSpuSkuAttrMapQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pssamq.querySpec()
	return sqlgraph.CountNodes(ctx, pssamq.driver, _spec)
}

func (pssamq *ProductSpuSkuAttrMapQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pssamq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (pssamq *ProductSpuSkuAttrMapQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productspuskuattrmap.Table,
			Columns: productspuskuattrmap.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productspuskuattrmap.FieldID,
			},
		},
		From:   pssamq.sql,
		Unique: true,
	}
	if fields := pssamq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productspuskuattrmap.FieldID)
		for i := range fields {
			if fields[i] != productspuskuattrmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pssamq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pssamq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pssamq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pssamq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, productspuskuattrmap.ValidColumn)
			}
		}
	}
	return _spec
}

func (pssamq *ProductSpuSkuAttrMapQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pssamq.driver.Dialect())
	t1 := builder.Table(productspuskuattrmap.Table)
	selector := builder.Select(t1.Columns(productspuskuattrmap.Columns...)...).From(t1)
	if pssamq.sql != nil {
		selector = pssamq.sql
		selector.Select(selector.Columns(productspuskuattrmap.Columns...)...)
	}
	for _, p := range pssamq.predicates {
		p(selector)
	}
	for _, p := range pssamq.order {
		p(selector, productspuskuattrmap.ValidColumn)
	}
	if offset := pssamq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pssamq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductSpuSkuAttrMapGroupBy is the group-by builder for ProductSpuSkuAttrMap entities.
type ProductSpuSkuAttrMapGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Aggregate(fns ...AggregateFunc) *ProductSpuSkuAttrMapGroupBy {
	pssamgb.fns = append(pssamgb.fns, fns...)
	return pssamgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pssamgb.path(ctx)
	if err != nil {
		return err
	}
	pssamgb.sql = query
	return pssamgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pssamgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pssamgb.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pssamgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) StringsX(ctx context.Context) []string {
	v, err := pssamgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pssamgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) StringX(ctx context.Context) string {
	v, err := pssamgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pssamgb.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pssamgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) IntsX(ctx context.Context) []int {
	v, err := pssamgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pssamgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) IntX(ctx context.Context) int {
	v, err := pssamgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pssamgb.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pssamgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pssamgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pssamgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pssamgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pssamgb.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pssamgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pssamgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pssamgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pssamgb *ProductSpuSkuAttrMapGroupBy) BoolX(ctx context.Context) bool {
	v, err := pssamgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pssamgb *ProductSpuSkuAttrMapGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pssamgb.fields {
		if !productspuskuattrmap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pssamgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pssamgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pssamgb *ProductSpuSkuAttrMapGroupBy) sqlQuery() *sql.Selector {
	selector := pssamgb.sql
	columns := make([]string, 0, len(pssamgb.fields)+len(pssamgb.fns))
	columns = append(columns, pssamgb.fields...)
	for _, fn := range pssamgb.fns {
		columns = append(columns, fn(selector, productspuskuattrmap.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(pssamgb.fields...)
}

// ProductSpuSkuAttrMapSelect is the builder for selecting fields of ProductSpuSkuAttrMap entities.
type ProductSpuSkuAttrMapSelect struct {
	*ProductSpuSkuAttrMapQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pssams *ProductSpuSkuAttrMapSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pssams.prepareQuery(ctx); err != nil {
		return err
	}
	pssams.sql = pssams.ProductSpuSkuAttrMapQuery.sqlQuery(ctx)
	return pssams.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pssams.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pssams.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pssams.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) StringsX(ctx context.Context) []string {
	v, err := pssams.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pssams.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) StringX(ctx context.Context) string {
	v, err := pssams.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pssams.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pssams.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) IntsX(ctx context.Context) []int {
	v, err := pssams.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pssams.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) IntX(ctx context.Context) int {
	v, err := pssams.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pssams.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pssams.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pssams.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pssams.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) Float64X(ctx context.Context) float64 {
	v, err := pssams.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pssams.fields) > 1 {
		return nil, errors.New("ent: ProductSpuSkuAttrMapSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pssams.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) BoolsX(ctx context.Context) []bool {
	v, err := pssams.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pssams *ProductSpuSkuAttrMapSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pssams.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{productspuskuattrmap.Label}
	default:
		err = fmt.Errorf("ent: ProductSpuSkuAttrMapSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pssams *ProductSpuSkuAttrMapSelect) BoolX(ctx context.Context) bool {
	v, err := pssams.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pssams *ProductSpuSkuAttrMapSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pssams.sqlQuery().Query()
	if err := pssams.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pssams *ProductSpuSkuAttrMapSelect) sqlQuery() sql.Querier {
	selector := pssams.sql
	selector.Select(selector.Columns(pssams.fields...)...)
	return selector
}
