// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skrshop/internal/data/ent/productspuskuattrmap"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductSpuSkuAttrMapCreate is the builder for creating a ProductSpuSkuAttrMap entity.
type ProductSpuSkuAttrMapCreate struct {
	config
	mutation *ProductSpuSkuAttrMapMutation
	hooks    []Hook
}

// SetCreateAt sets the "create_at" field.
func (pssamc *ProductSpuSkuAttrMapCreate) SetCreateAt(t time.Time) *ProductSpuSkuAttrMapCreate {
	pssamc.mutation.SetCreateAt(t)
	return pssamc
}

// SetUpdateAt sets the "update_at" field.
func (pssamc *ProductSpuSkuAttrMapCreate) SetUpdateAt(t time.Time) *ProductSpuSkuAttrMapCreate {
	pssamc.mutation.SetUpdateAt(t)
	return pssamc
}

// SetStatus sets the "status" field.
func (pssamc *ProductSpuSkuAttrMapCreate) SetStatus(i int8) *ProductSpuSkuAttrMapCreate {
	pssamc.mutation.SetStatus(i)
	return pssamc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pssamc *ProductSpuSkuAttrMapCreate) SetNillableStatus(i *int8) *ProductSpuSkuAttrMapCreate {
	if i != nil {
		pssamc.SetStatus(*i)
	}
	return pssamc
}

// Mutation returns the ProductSpuSkuAttrMapMutation object of the builder.
func (pssamc *ProductSpuSkuAttrMapCreate) Mutation() *ProductSpuSkuAttrMapMutation {
	return pssamc.mutation
}

// Save creates the ProductSpuSkuAttrMap in the database.
func (pssamc *ProductSpuSkuAttrMapCreate) Save(ctx context.Context) (*ProductSpuSkuAttrMap, error) {
	var (
		err  error
		node *ProductSpuSkuAttrMap
	)
	pssamc.defaults()
	if len(pssamc.hooks) == 0 {
		if err = pssamc.check(); err != nil {
			return nil, err
		}
		node, err = pssamc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductSpuSkuAttrMapMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pssamc.check(); err != nil {
				return nil, err
			}
			pssamc.mutation = mutation
			node, err = pssamc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pssamc.hooks) - 1; i >= 0; i-- {
			mut = pssamc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pssamc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pssamc *ProductSpuSkuAttrMapCreate) SaveX(ctx context.Context) *ProductSpuSkuAttrMap {
	v, err := pssamc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pssamc *ProductSpuSkuAttrMapCreate) defaults() {
	if _, ok := pssamc.mutation.Status(); !ok {
		v := productspuskuattrmap.DefaultStatus
		pssamc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pssamc *ProductSpuSkuAttrMapCreate) check() error {
	if _, ok := pssamc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	if _, ok := pssamc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New("ent: missing required field \"update_at\"")}
	}
	if _, ok := pssamc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	return nil
}

func (pssamc *ProductSpuSkuAttrMapCreate) sqlSave(ctx context.Context) (*ProductSpuSkuAttrMap, error) {
	_node, _spec := pssamc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pssamc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pssamc *ProductSpuSkuAttrMapCreate) createSpec() (*ProductSpuSkuAttrMap, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductSpuSkuAttrMap{config: pssamc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productspuskuattrmap.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productspuskuattrmap.FieldID,
			},
		}
	)
	if value, ok := pssamc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productspuskuattrmap.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := pssamc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productspuskuattrmap.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := pssamc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productspuskuattrmap.FieldStatus,
		})
		_node.Status = value
	}
	return _node, _spec
}

// ProductSpuSkuAttrMapCreateBulk is the builder for creating many ProductSpuSkuAttrMap entities in bulk.
type ProductSpuSkuAttrMapCreateBulk struct {
	config
	builders []*ProductSpuSkuAttrMapCreate
}

// Save creates the ProductSpuSkuAttrMap entities in the database.
func (pssamcb *ProductSpuSkuAttrMapCreateBulk) Save(ctx context.Context) ([]*ProductSpuSkuAttrMap, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pssamcb.builders))
	nodes := make([]*ProductSpuSkuAttrMap, len(pssamcb.builders))
	mutators := make([]Mutator, len(pssamcb.builders))
	for i := range pssamcb.builders {
		func(i int, root context.Context) {
			builder := pssamcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductSpuSkuAttrMapMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pssamcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pssamcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pssamcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pssamcb *ProductSpuSkuAttrMapCreateBulk) SaveX(ctx context.Context) []*ProductSpuSkuAttrMap {
	v, err := pssamcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
