// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productbrands"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductBrandsDelete is the builder for deleting a ProductBrands entity.
type ProductBrandsDelete struct {
	config
	hooks    []Hook
	mutation *ProductBrandsMutation
}

// Where adds a new predicate to the ProductBrandsDelete builder.
func (pbd *ProductBrandsDelete) Where(ps ...predicate.ProductBrands) *ProductBrandsDelete {
	pbd.mutation.predicates = append(pbd.mutation.predicates, ps...)
	return pbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pbd *ProductBrandsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pbd.hooks) == 0 {
		affected, err = pbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductBrandsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pbd.mutation = mutation
			affected, err = pbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pbd.hooks) - 1; i >= 0; i-- {
			mut = pbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pbd *ProductBrandsDelete) ExecX(ctx context.Context) int {
	n, err := pbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pbd *ProductBrandsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productbrands.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productbrands.FieldID,
			},
		},
	}
	if ps := pbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pbd.driver, _spec)
}

// ProductBrandsDeleteOne is the builder for deleting a single ProductBrands entity.
type ProductBrandsDeleteOne struct {
	pbd *ProductBrandsDelete
}

// Exec executes the deletion query.
func (pbdo *ProductBrandsDeleteOne) Exec(ctx context.Context) error {
	n, err := pbdo.pbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productbrands.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pbdo *ProductBrandsDeleteOne) ExecX(ctx context.Context) {
	pbdo.pbd.ExecX(ctx)
}
