// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productattr"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttrUpdate is the builder for updating ProductAttr entities.
type ProductAttrUpdate struct {
	config
	hooks    []Hook
	mutation *ProductAttrMutation
}

// Where adds a new predicate for the ProductAttrUpdate builder.
func (pau *ProductAttrUpdate) Where(ps ...predicate.ProductAttr) *ProductAttrUpdate {
	pau.mutation.predicates = append(pau.mutation.predicates, ps...)
	return pau
}

// SetStatus sets the "status" field.
func (pau *ProductAttrUpdate) SetStatus(i int8) *ProductAttrUpdate {
	pau.mutation.ResetStatus()
	pau.mutation.SetStatus(i)
	return pau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pau *ProductAttrUpdate) SetNillableStatus(i *int8) *ProductAttrUpdate {
	if i != nil {
		pau.SetStatus(*i)
	}
	return pau
}

// AddStatus adds i to the "status" field.
func (pau *ProductAttrUpdate) AddStatus(i int8) *ProductAttrUpdate {
	pau.mutation.AddStatus(i)
	return pau
}

// SetCreateAt sets the "create_at" field.
func (pau *ProductAttrUpdate) SetCreateAt(t time.Time) *ProductAttrUpdate {
	pau.mutation.SetCreateAt(t)
	return pau
}

// SetUpdateAt sets the "update_at" field.
func (pau *ProductAttrUpdate) SetUpdateAt(t time.Time) *ProductAttrUpdate {
	pau.mutation.SetUpdateAt(t)
	return pau
}

// Mutation returns the ProductAttrMutation object of the builder.
func (pau *ProductAttrUpdate) Mutation() *ProductAttrMutation {
	return pau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pau *ProductAttrUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pau.hooks) == 0 {
		affected, err = pau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttrMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pau.mutation = mutation
			affected, err = pau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pau.hooks) - 1; i >= 0; i-- {
			mut = pau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pau *ProductAttrUpdate) SaveX(ctx context.Context) int {
	affected, err := pau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pau *ProductAttrUpdate) Exec(ctx context.Context) error {
	_, err := pau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pau *ProductAttrUpdate) ExecX(ctx context.Context) {
	if err := pau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pau *ProductAttrUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productattr.Table,
			Columns: productattr.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattr.FieldID,
			},
		},
	}
	if ps := pau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pau.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productattr.FieldStatus,
		})
	}
	if value, ok := pau.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productattr.FieldStatus,
		})
	}
	if value, ok := pau.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldCreateAt,
		})
	}
	if value, ok := pau.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productattr.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// ProductAttrUpdateOne is the builder for updating a single ProductAttr entity.
type ProductAttrUpdateOne struct {
	config
	hooks    []Hook
	mutation *ProductAttrMutation
}

// SetStatus sets the "status" field.
func (pauo *ProductAttrUpdateOne) SetStatus(i int8) *ProductAttrUpdateOne {
	pauo.mutation.ResetStatus()
	pauo.mutation.SetStatus(i)
	return pauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pauo *ProductAttrUpdateOne) SetNillableStatus(i *int8) *ProductAttrUpdateOne {
	if i != nil {
		pauo.SetStatus(*i)
	}
	return pauo
}

// AddStatus adds i to the "status" field.
func (pauo *ProductAttrUpdateOne) AddStatus(i int8) *ProductAttrUpdateOne {
	pauo.mutation.AddStatus(i)
	return pauo
}

// SetCreateAt sets the "create_at" field.
func (pauo *ProductAttrUpdateOne) SetCreateAt(t time.Time) *ProductAttrUpdateOne {
	pauo.mutation.SetCreateAt(t)
	return pauo
}

// SetUpdateAt sets the "update_at" field.
func (pauo *ProductAttrUpdateOne) SetUpdateAt(t time.Time) *ProductAttrUpdateOne {
	pauo.mutation.SetUpdateAt(t)
	return pauo
}

// Mutation returns the ProductAttrMutation object of the builder.
func (pauo *ProductAttrUpdateOne) Mutation() *ProductAttrMutation {
	return pauo.mutation
}

// Save executes the query and returns the updated ProductAttr entity.
func (pauo *ProductAttrUpdateOne) Save(ctx context.Context) (*ProductAttr, error) {
	var (
		err  error
		node *ProductAttr
	)
	if len(pauo.hooks) == 0 {
		node, err = pauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttrMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pauo.mutation = mutation
			node, err = pauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pauo.hooks) - 1; i >= 0; i-- {
			mut = pauo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pauo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pauo *ProductAttrUpdateOne) SaveX(ctx context.Context) *ProductAttr {
	node, err := pauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pauo *ProductAttrUpdateOne) Exec(ctx context.Context) error {
	_, err := pauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pauo *ProductAttrUpdateOne) ExecX(ctx context.Context) {
	if err := pauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pauo *ProductAttrUpdateOne) sqlSave(ctx context.Context) (_node *ProductAttr, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   productattr.Table,
			Columns: productattr.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattr.FieldID,
			},
		},
	}
	id, ok := pauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing ProductAttr.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := pauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pauo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productattr.FieldStatus,
		})
	}
	if value, ok := pauo.mutation.AddedStatus(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productattr.FieldStatus,
		})
	}
	if value, ok := pauo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldCreateAt,
		})
	}
	if value, ok := pauo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldUpdateAt,
		})
	}
	_node = &ProductAttr{config: pauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productattr.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
