// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"skrshop/internal/data/ent/productattr"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttrCreate is the builder for creating a ProductAttr entity.
type ProductAttrCreate struct {
	config
	mutation *ProductAttrMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (pac *ProductAttrCreate) SetStatus(i int8) *ProductAttrCreate {
	pac.mutation.SetStatus(i)
	return pac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pac *ProductAttrCreate) SetNillableStatus(i *int8) *ProductAttrCreate {
	if i != nil {
		pac.SetStatus(*i)
	}
	return pac
}

// SetCreateAt sets the "create_at" field.
func (pac *ProductAttrCreate) SetCreateAt(t time.Time) *ProductAttrCreate {
	pac.mutation.SetCreateAt(t)
	return pac
}

// SetUpdateAt sets the "update_at" field.
func (pac *ProductAttrCreate) SetUpdateAt(t time.Time) *ProductAttrCreate {
	pac.mutation.SetUpdateAt(t)
	return pac
}

// Mutation returns the ProductAttrMutation object of the builder.
func (pac *ProductAttrCreate) Mutation() *ProductAttrMutation {
	return pac.mutation
}

// Save creates the ProductAttr in the database.
func (pac *ProductAttrCreate) Save(ctx context.Context) (*ProductAttr, error) {
	var (
		err  error
		node *ProductAttr
	)
	pac.defaults()
	if len(pac.hooks) == 0 {
		if err = pac.check(); err != nil {
			return nil, err
		}
		node, err = pac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttrMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pac.check(); err != nil {
				return nil, err
			}
			pac.mutation = mutation
			node, err = pac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pac.hooks) - 1; i >= 0; i-- {
			mut = pac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pac *ProductAttrCreate) SaveX(ctx context.Context) *ProductAttr {
	v, err := pac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pac *ProductAttrCreate) defaults() {
	if _, ok := pac.mutation.Status(); !ok {
		v := productattr.DefaultStatus
		pac.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pac *ProductAttrCreate) check() error {
	if _, ok := pac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New("ent: missing required field \"status\"")}
	}
	if _, ok := pac.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New("ent: missing required field \"create_at\"")}
	}
	if _, ok := pac.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New("ent: missing required field \"update_at\"")}
	}
	return nil
}

func (pac *ProductAttrCreate) sqlSave(ctx context.Context) (*ProductAttr, error) {
	_node, _spec := pac.createSpec()
	if err := sqlgraph.CreateNode(ctx, pac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pac *ProductAttrCreate) createSpec() (*ProductAttr, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductAttr{config: pac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productattr.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattr.FieldID,
			},
		}
	)
	if value, ok := pac.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: productattr.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := pac.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := pac.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattr.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	return _node, _spec
}

// ProductAttrCreateBulk is the builder for creating many ProductAttr entities in bulk.
type ProductAttrCreateBulk struct {
	config
	builders []*ProductAttrCreate
}

// Save creates the ProductAttr entities in the database.
func (pacb *ProductAttrCreateBulk) Save(ctx context.Context) ([]*ProductAttr, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pacb.builders))
	nodes := make([]*ProductAttr, len(pacb.builders))
	mutators := make([]Mutator, len(pacb.builders))
	for i := range pacb.builders {
		func(i int, root context.Context) {
			builder := pacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductAttrMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pacb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pacb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pacb *ProductAttrCreateBulk) SaveX(ctx context.Context) []*ProductAttr {
	v, err := pacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
