// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"skrshop/internal/data/ent/predicate"
	"skrshop/internal/data/ent/productattrvalue"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttrValueDelete is the builder for deleting a ProductAttrValue entity.
type ProductAttrValueDelete struct {
	config
	hooks    []Hook
	mutation *ProductAttrValueMutation
}

// Where adds a new predicate to the ProductAttrValueDelete builder.
func (pavd *ProductAttrValueDelete) Where(ps ...predicate.ProductAttrValue) *ProductAttrValueDelete {
	pavd.mutation.predicates = append(pavd.mutation.predicates, ps...)
	return pavd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pavd *ProductAttrValueDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pavd.hooks) == 0 {
		affected, err = pavd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttrValueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pavd.mutation = mutation
			affected, err = pavd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pavd.hooks) - 1; i >= 0; i-- {
			mut = pavd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pavd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pavd *ProductAttrValueDelete) ExecX(ctx context.Context) int {
	n, err := pavd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pavd *ProductAttrValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productattrvalue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattrvalue.FieldID,
			},
		},
	}
	if ps := pavd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pavd.driver, _spec)
}

// ProductAttrValueDeleteOne is the builder for deleting a single ProductAttrValue entity.
type ProductAttrValueDeleteOne struct {
	pavd *ProductAttrValueDelete
}

// Exec executes the deletion query.
func (pavdo *ProductAttrValueDeleteOne) Exec(ctx context.Context) error {
	n, err := pavdo.pavd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productattrvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pavdo *ProductAttrValueDeleteOne) ExecX(ctx context.Context) {
	pavdo.pavd.ExecX(ctx)
}
