// Code generated by entc, DO NOT EDIT.

package productbrands

const (
	// Label holds the string label denoting the productbrands type in the database.
	Label = "product_brands"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"

	// Table holds the table name of the productbrands in the database.
	Table = "product_brands"
)

// Columns holds all SQL columns for productbrands fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDesc,
	FieldLogoURL,
	FieldStatus,
	FieldCreateAt,
	FieldUpdateAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDesc holds the default value on creation for the "desc" field.
	DefaultDesc string
	// DescValidator is a validator for the "desc" field. It is called by the builders before save.
	DescValidator func(string) error
	// DefaultLogoURL holds the default value on creation for the "logo_url" field.
	DefaultLogoURL string
	// LogoURLValidator is a validator for the "logo_url" field. It is called by the builders before save.
	LogoURLValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
)
